# Simple pipeline that should have the same results as .github/workflows/build-with-fake.yml

trigger:
- master
# Also trigger on this branch while we're testing our script
- azure-pipelines

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Setup .NET Core'
  inputs:
    packageType: sdk
    version: 2.2.401
    installationPath: $(Agent.ToolsDirectory)/dotnet
- script: dotnet tool install --tool-path .fake fake-cli
  displayName: Set up FAKE build tool
- script: .fake/fake build
  displayName: Build with FAKE
