name: Build master

on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up FAKE build tool
      run: dotnet tool install --tool-path .fake fake-cli
    - name: Build with FAKE (Linux/OSX)
      if: runner.os != 'Windows'
      run: ls -lR $DOTNET_ROOT
      env:
        # Work around https://github.com/actions/setup-dotnet/issues/29
        DOTNET_ROOT: ${{ runner.tool_cache }}/dncs/2.2.401/x64
    - name: Build with FAKE (Windows)
      if: runner.os == 'Windows'
      run: .fake\fake build
      env:
        # Work around https://github.com/actions/setup-dotnet/issues/29
        DOTNET_ROOT: ${{ runner.tool_cache }}/dncs/2.2.401/x64
