name: Build master

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.401
    - name: Set up FAKE as global tool
      run: dotnet tool install -g fake-cli
    - name: Build with FAKE
      run: fake build
